version: '3'

volumes:
  db:


services:
# FRONTEND
  frontend1:
    image: craybor/balancefy-frontend:latest

  frontend2:
    image: craybor/balancefy-frontend:latest

  loadbalance:
    image: nginx:latest
    volumes:
      - ./lb/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./lb/cert.pem:/etc/nginx/conf.d/
      # - ./lb/privkey.pem:/etc/nginx/conf.d/
    depends_on:
      - frontend1
      - frontend2
    ports:
      - 8081:80

# BACKEND
  backend:
    image: craybor/balancefy-backend:latest
    restart: always
    depends_on:
      - balancefydb
    ports:
      - 8080:8080
    

  balancefydb:
    image: postgres:10.5
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/mysql
      - ./db/migration.sql:/docker-entrypoint-initdb.d/migration.sql